import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'transparent',
    position: 'relative',
  },
  bgLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    // Android can fail to render negative zIndex layers; keep this non-negative
    // and rely on render order (bg layers are mounted before content) plus
    // pointerEvents="none" on the layer views.
    zIndex: 0,
  },
  sun: {
    position: 'absolute',
    width: 260,
    height: 260,
    borderRadius: 200,
    backgroundColor: '#FFD54F',
    bottom: -195,
    left: -40,
    opacity: 0.95,
  },
  sunGlow: {
    position: 'absolute',
    width: 460,
    height: 460,
    borderRadius: 300,
    backgroundColor: 'rgba(255,213,79,0.08)',
    bottom: -345,
    left: -140,
  },
  // clouds should sit behind the earth; keep zIndex low
  cloud: {
    position: 'absolute',
    backgroundColor: 'rgba(255,255,255,0.9)',
    opacity: 0.9,
    zIndex: 0,
  },
  cloud1: {
    width: 140,
    height: 44,
    borderRadius: 22,
    top: 36,
    left: 38,
    opacity: 0.85,
  },
  cloud2: {
    width: 180,
    height: 52,
    borderRadius: 26,
    top: 18,
    left: 120,
    opacity: 0.6,
  },
  cloud3: {
    width: 100,
    height: 36,
    borderRadius: 18,
    top: 76,
    left: 200,
    opacity: 0.75,
  },
  blackHole: {
    position: 'absolute',
    width: 260,
    height: 260,
    borderRadius: 200,
    backgroundColor: '#07070A',
    bottom: -195,
    left: '50%',
    transform: [{ translateX: -130 }],
  },
  blackHoleHalo: {
    position: 'absolute',
    width: 420,
    height: 420,
    borderRadius: 210,
    backgroundColor: 'rgba(167,139,250,0.06)',
    bottom: -260,
    left: '50%',
    transform: [{ translateX: -210 }],
  },
  blackHoleRing: {
    position: 'absolute',
    width: 340,
    height: 340,
    borderRadius: 220,
    borderWidth: 10,
    borderColor: 'rgba(167,139,250,0.18)',
    bottom: -255,
    left: '50%',
    transform: [{ translateX: -170 }],
  },

  blackHoleCore: {
    position: 'absolute',
    left: '50%',
    top: '50%',
    width: 40,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#000',
    borderWidth: 6,
    borderColor: 'rgba(90,20,160,0.8)'
  },
  earth: {
    position: 'absolute',
    width: 300,
    height: 300,
    borderRadius: 200,
    backgroundColor: '#0B3D91',
    bottom: -210,
    right: -80,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    zIndex: 5,
    elevation: 8,
    overflow: 'hidden',
  },
  earthLand1: {
    position: 'absolute',
    width: 120,
    height: 60,
    backgroundColor: '#2CA02C',
    borderRadius: 30,
    transform: [{ rotate: '-15deg' }],
    top: 70,
    left: 40,
    opacity: 0.95,
  },
  earthLand2: {
    position: 'absolute',
    width: 80,
    height: 40,
    backgroundColor: '#2CA02C',
    borderRadius: 20,
    transform: [{ rotate: '25deg' }],
    top: 140,
    left: 180,
    opacity: 0.95,
  },
  earthCloud: {
    position: 'absolute',
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 20,
    zIndex: 20,
    elevation: 16,
  },
  earthCloud1: {
    width: 140,
    height: 44,
    top: 30,
    left: 20,
    opacity: 0.9,
  },
  earthCloud2: {
    width: 180,
    height: 52,
    top: 90,
    left: 60,
    opacity: 0.8,
  },
  earthCloud3: {
    width: 100,
    height: 36,
    top: 150,
    left: 140,
    opacity: 0.85,
  },
  cloudGroup: {
    position: 'absolute',
    zIndex: 20,
    elevation: 16,
    width: 90,
    height: 42,
  },
  cloudGroup1: { left: 8, top: 20 },
  cloudGroup2: { left: 40, top: 70 },
  cloudGroup3: { left: 120, top: 28 },
  cloudGroup4: { left: 160, top: 98 },
  cloudGroup5: { left: 12, top: 140 },
  cloudGroup6: { left: 88, top: 170 },
  cloudGroup7: { left: 190, top: 50 },
  cloudGroup8: { left: 220, top: 120 },
  cloudPuff: {
    position: 'absolute',
    backgroundColor: 'rgba(255,255,255,0.96)',
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
  },
  puffLarge: { width: 48, height: 30 },
  puffMed: { width: 36, height: 24 },
  puffSmall: { width: 26, height: 18 },
  page: {
    padding: 20,
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  pageTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: 'rgba(167,139,250,0.95)'
  },
  pageSubtitle: {
    marginTop: 6,
    color: '#C9B8FF',
    marginBottom: 12,
  },
  fabOverlay: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 6,
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    zIndex: 20,
  },
  placeholderCard: {
    marginTop: 18,
    width: '100%',
    maxWidth: 420,
    height: 220,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.03)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)'
  },
  placeholderText: {
    color: '#EDE7FF'
  },
  card: {
    width: '100%',
    maxWidth: 420,
    gap: 12,
    marginTop: 16,
  },
  actionButton: {
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.10)',
  },
  actionButtonPressed: {
    backgroundColor: 'rgba(255, 255, 255, 0.10)',
  },
  actionButtonText: {
    color: 'rgba(255, 255, 255, 0.92)',
    fontSize: 16,
    fontWeight: '600'
  },
  navbar: {
    height: 68,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.03)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: 12,
    backgroundColor: 'transparent'
  },
  navItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center'
  },
  navLabel: {
    color: 'rgba(255,255,255,0.7)',
    fontWeight: '700'
  },
  navLabelActive: {
    color: '#4abfd7',
    fontWeight: '800',
  },
  ball: {
    backgroundColor: "#000", // black background
    borderRadius: 22,
    width: 44,
    height: 44,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  plusContainer: {
    justifyContent: "center",
    alignItems: "center",
  },
  plus: {
    color: "#fff", // white plus
    fontSize: 24,
    fontWeight: "700",
  },
});
