import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  slide: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  slideTop: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: 18,
    paddingTop: 28,
  },
  networkSlideCentered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    paddingTop: 80,
  },
  title: {
    fontSize: 24,
    fontWeight: '800',
    marginBottom: 12,
    color: '#7C4DFF',
    textShadowColor: '#7C4DFF',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
    letterSpacing: 0.4,
  },
  titleSmall: {
    fontSize: 20,
    marginBottom: 8,
  },
  titleRow: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'column',
  },
  text: {
    fontSize: 17,
    color: '#C9B8FF',
    textAlign: 'center',
    lineHeight: 24,
    paddingHorizontal: 8,
  },
  galactic: {
    color: '#9BE2FF',
    fontWeight: '700',
    fontSize: 22,
    textShadowColor: '#7C4DFF',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 12,
  },
  arrow: {
    fontSize: 40,
    color: '#7C4DFF',
    textAlign: 'center',
    marginTop: 18,
    textShadowColor: '#7C4DFF',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 10,
  },
  eyesRow: {
    flexDirection: 'row',
    marginTop: 18,
  },
  eyeWrapper: {
    width: 56,
    height: 36,
    marginHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  eyesContainer: {
    width: 220,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  eyeSclera: {
    width: 44,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(124,77,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  irisWrapper: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  iris: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#4DFFFF',
  },
  pupil: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#000',
  },
  eyelidTop: {
    position: 'absolute',
    top: 0,
    width: 44,
    left: (56 - 44) / 2,
    backgroundColor: '#7C4DFF',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    overflow: 'hidden',
  },
  eyelidBottom: {
    position: 'absolute',
    bottom: 0,
    width: 44,
    left: (56 - 44) / 2,
    backgroundColor: '#7C4DFF',
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    overflow: 'hidden',
  },
  blindfold: {
    position: 'absolute',
    width: 180,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#2E0066',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    top: -20,
    opacity: 1,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.12)',
  },
  blindfoldText: {
    color: 'rgba(237,231,255,0.55)',
    fontWeight: '700',
    fontSize: 16,
    letterSpacing: 2,
  },
  actions: {
    marginTop: 24,
    flexDirection: 'row',
  },
  button: {
    marginHorizontal: 8,
    minWidth: 110,
    paddingHorizontal: 6,
  },
  actionsColumn: {
    marginTop: 24,
    width: '100%',
    alignItems: 'center',
  },
  actionsRow: {
    marginTop: 12,
    flexDirection: 'row',
  },
  mnemonicInput: {
    width: '100%',
    minHeight: 88,
    borderWidth: 2,
    borderColor: 'rgba(201,184,255,0.35)',
    backgroundColor: 'rgba(46,0,102,0.06)',
    color: '#EDE7FF',
    padding: 12,
    borderRadius: 8,
    textAlignVertical: 'top',
  },
  inputValid: {
    borderColor: '#00C853',
  },
  inputInvalid: {
    borderColor: '#FF1744',
  },
  glassButton: {
    paddingVertical: 12,
    paddingHorizontal: 22,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#7C4DFF',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 16,
    elevation: 4,
  },
  generateButton: {
    backgroundColor: 'rgba(124,77,255,0.20)',
    borderColor: 'rgba(124,77,255,0.36)',
  },
  saveButton: {
    backgroundColor: 'rgba(0,200,83,0.18)',
    borderColor: 'rgba(0,200,83,0.30)',
  },
  glassButtonDisabled: {
    opacity: 0.7,
    backgroundColor: 'rgba(255,255,255,0.03)'
  },
  glassButtonText: {
    color: '#FFFFFF',
    fontWeight: '800',
    letterSpacing: 0.6,
    fontSize: 15,
  },
  glassButtonTextDisabled: {
    color: 'rgba(255,255,255,0.72)',
  },
  networkOption: {
    marginVertical: 8,
    padding: 12,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.02)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.04)',
  },
  networkOptionSelected: {
    backgroundColor: 'rgba(124,77,255,0.22)',
    borderColor: 'rgba(124,77,255,0.36)',
  },
  networkOptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  networkBullet: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: 'rgba(255,255,255,0.14)',
    marginRight: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  networkBulletSelected: {
    backgroundColor: '#FFFFFF',
  },
  networkLabel: {
    color: '#EDE7FF',
    fontWeight: '700',
    fontSize: 15,
  },
  networkDesc: {
    color: '#C9B8FF',
    fontSize: 12,
  },
  networkCheck: {
    color: '#FFFFFF',
    fontWeight: '800',
    marginLeft: 12,
  },
  swipeTrack: {
    width: 84,
    height: 18,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(124,77,255,0.12)',
    overflow: 'hidden',
  },
  swipeDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#EDE7FF',
    margin: 2,
  },
  swipeText: {
    marginTop: 8,
    color: '#C9B8FF',
    fontWeight: '700',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  modalContent: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 16,
    padding: 18,
    backgroundColor: 'rgba(46,0,102,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    shadowColor: '#7C4DFF',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 24,
    elevation: 8,
  },
  modalTitle: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 8,
  },
  modalMessage: {
    color: '#EDE7FF',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 18,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  modalButton: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 999,
    marginLeft: 8,
  },
  modalButtonText: {
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  modalCancel: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
  },
  modalCancelText: {
    color: '#C9B8FF',
  },
  modalConfirm: {
    backgroundColor: 'rgba(124,77,255,0.95)',
  },
  modalConfirmText: {
    color: '#FFFFFF',
  },
  savedOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    padding: 24,
  },
  savedBubble: {
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 12,
    backgroundColor: 'rgba(124,77,255,0.98)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    shadowColor: '#7C4DFF',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 6,
  },
  savedText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 15,
  },
  loadingOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.45)',
    borderRadius: 12,
  },
  loadingOverlayText: {
    marginTop: 12,
    color: '#EDE7FF',
    fontSize: 14,
  },

});